# Generated by Django 6.0.2 on 2026-03-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_match_status_alter_match_user_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interested_in',
            field=models.CharField(choices=[('A', 'Все'), ('M', 'Мужчина'), ('F', 'Женщина')], default='A', max_length=1),
        ),
    ]
